<div class="row">
    <div class="col-md-9">
        <h1 class="display-4">Blocked users</h1>
    </div>
</div>

<table class="table">
    <thead>
    <th>login</th>
    <th>posts</th>
    <th>comments</th>
    <th></th>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user) { ?>
        <tr id="row-<?php echo $user->getId() ?>">
            <td><?php echo $user->getLogin() ?></td>
            <td><?php echo $amountOfPosts = $this->entityManager->getRepository(\Application\Entity\Post::class)
                    ->getAmountPostsByUser($user->getId());
                ?></td>
            <td><?php echo $amountOfComments = $this->entityManager->getRepository(\Application\Entity\Comment::class)
                    ->getAmountCommentsByUserId($user->getId()); ?></td>
            <td>
                <button user-id="<?php echo $user->getId() ?>" class="unblock">
                    unblock
                </button>
                <a href="/post/author/<?php echo $user->getId() ?>">
                    post
                </a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->users,
    'Sliding',
    'application/partial/paginator',
    ['route' => 'profile', 'action' => 'blocked']);
?>

<script>
    $(".unblock").click(function () {
        let userId = $(this).attr('user-id');
        if (confirm("Unblock this user?")) {
            $.ajax({
                url: '/user/unblock',
                type: "POST",
                data: {userId: userId}
            }).done(function (data) {
                if (data){
                    $("#row-" + userId).hide();
                }
            });
        }
    });
</script>
