<?php
$form = $this->form;
$form->prepare();

$form->get('old-password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('re-password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-outline-success']);

?>
<h1>Change password</h1>

<?php if (isset($this->message)) { ?>
    <p><?php echo $this->message; ?>
    <a href="/profile">Back to profile</a>
    </p>
<?php } ?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('old-password'));
            echo $this->formElement($form->get('old-password'));
            echo $this->formElementErrors($form->get('old-password'));
            ?>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('password'));
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('re-password'));
            echo $this->formElement($form->get('re-password'));
            echo $this->formElementErrors($form->get('re-password'));
            ?>
        </div>

        <?php
        echo $this->formElement($form->get('submit'));
        ?>

        <?php echo $this->form()->closeTag($form) ?>
    </div>
</div>