<div class="row">
    <div class="col-md-9">
        <h1 class="display-4">My posts</h1>
    </div>
    <div class="col-md-3">
        <a href="/post/add" class="btn btn-outline-dark">Create new post</a>
    </div>
</div>

<div class="list-group">
    <?php foreach ($this->posts as $post) { ?>
        <li class="list-group-item justify-content-between align-items-center">
            <div class="row">
                <div class="col-md-9">
                    <h5>
                        <a href="/post/one/<?php echo $post->getId() ?>">
                            <?php echo $this->escapeHtml($post->getTitle()) ?>
                        </a>
                    </h5>
                </div>
                <div class="col-md-1">
                    <span class="badge badge-info badge-pill">
                        <?php echo $this->escapeHtml($post->getDate()) ?>
                    </span>
                </div>
            </div>
            <?php echo $this->escapeHtml($post->getShortContent()) ?>
        </li>
    <?php } ?>
</div>

<?php
echo $this->paginationControl($this->posts,
    'Sliding',
    'application/partial/paginator',
    ['route' => 'profile', 'action' => 'posts']);
?>