<?php
$form = $this->form;
$form->prepare();

$form->get('login')->setAttributes([
    'class' => 'form-control',
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-outline-success']);

?>
<h1>Log in</h1>
<?php
if (isset($this->message)) { ?>

    <h4><?php echo $this->message ?></h4>

    <a href="<?php echo $this->url('logout') ?>">Log out</a>

<?php } else { ?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->form()->openTag($form) ?>
            <div class="form-group">
                <?php
                echo $this->formLabel($form->get('login'));
                echo $this->formElement($form->get('login'));
                echo $this->formElementErrors($form->get('login'));
                ?>
            </div>

            <div class="form-group">
                <?php
                echo $this->formLabel($form->get('password'));
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
                ?>
            </div>

            <?php
            echo $this->formElement($form->get('submit'));
            ?>

            <?php echo $this->form()->closeTag($form) ?>
        </div>
    </div>
<?php } ?>

