<?php
$form = $this->form;
$form->prepare();

$form->get('login')->setAttributes([
    'class' => 'form-control',
]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('re-password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-outline-success']);

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="display-4">Registration</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('login'));
            echo $this->formElement($form->get('login'));
            echo $this->formElementErrors($form->get('login'));
            ?>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('email'));
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('password'));
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </div>

        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('re-password'));
            echo $this->formElement($form->get('re-password'));
            echo $this->formElementErrors($form->get('re-password'));
            ?>
        </div>

        <?php
        echo $this->formElement($form->get('submit'));
        ?>

        <?php echo $this->form()->closeTag($form) ?>
    </div>
</div>

