<div class="row">
    <div class="col-md-9">
        <h1 class="display-4">Posts by
            <?php echo $this->escapeHtml($this->author->getLogin()) ?>
        </h1>
    </div>
    <div class="col-md-3">
        <a href="/post/add" class="btn btn-outline-dark">Create new post</a>
    </div>
</div>

<div class="main">
    <div class="list-group">
        <?php foreach ($this->posts as $post) { ?>
            <li class="list-group-item justify-content-between align-items-center">
                <div class="row">
                    <div class="col-md-9">
                        <h5>
                            <a href="/post/one/<?php echo $post->getId() ?>">
                                <?php echo $this->escapeHtml($post->getTitle()) ?>
                            </a>
                        </h5>
                    </div>
                    <div class="col-md-1">
                    <span class="badge badge-info badge-pill">
                        <a href="/post/author/<?php echo $this->escapeHtml($post->getUser()->getId())?>">
                            <?php echo $this->escapeHtml($post->getUser()->getLogin()) ?>
                        </a>
                        <?php echo $this->escapeHtml($post->getDate()) ?>
                    </span>
                    </div>
                </div>
                <?php echo $this->escapeHtml($post->getShortContent()) ?>
            </li>
        <?php } ?>

    </div>


    <br>
    <?php
    echo $this->paginationControl($this->posts,
        'Sliding',
        'application/partial/paginator',
        ['params' => $this->params]);
    ?>
</div>

<div class="sidenav">
    <div class="card">
        <div class="card-header">
            <h5>Popular Tags</h5>
        </div>
        <div class="card-body">
            <?php foreach ($this->tagCloud as $tagId => $tag) { ?>

                <a href="<?= $this->url('post', ['action' => 'author', 'id' => $this->author->getId()],
                    ['query' => ['tag' => $tagId]]); ?>">

                    <span style="font-size:<?= $this->escapeHtml(0.9 + $tag['count'] * 2) ?>em">
                        <?= $this->escapeHtml($tag['name']); ?>
                    </span>

                </a>

            <?php } ?>
        </div>
    </div>
</div>