<div class="row">
    <div class="col-md-9">
        <h1 class="display-4">Posts</h1>
    </div>
    <div class="col-md-3">
        <a href="/post/add" class="btn btn-outline-dark">Create new post</a>
    </div>
</div>

<div class="main">
    <div class="list-group">
        <?php foreach ($this->posts as $post) { ?>
            <li class="list-group-item justify-content-between align-items-center">
                <div class="row">
                    <div class="col-md-9">
                        <h5>
                            <a href="/post/one/<?php echo $post->getId() ?>">
                                <?php echo $this->escapeHtml($post->getTitle()) ?>
                            </a>
                        </h5>
                    </div>
                    <div class="col-md-1">
                    <span class="badge badge-info badge-pill">
                        <?php echo $this->escapeHtml($post->getUser()->getLogin()) ?>
                        <?php echo $this->escapeHtml($post->getDate()) ?>
                    </span>
                    </div>
                </div>
                <?php echo $this->escapeHtml($post->getShortContent()) ?>
            </li>
        <?php } ?>

    </div>


    <br>
    <?php
    echo $this->paginationControl($this->posts,
        'Sliding',
        'application/partial/paginator',
        ['params' => $this->params]);
    ?>
</div>

<div class="sidenav">
    <div class="card">
        <div class="card-header">
            <h5>Popular Tags</h5>
        </div>
        <div class="card-body">
            <?php foreach ($this->tagCloud as $tagId => $tag) { ?>

                <a href="<?= $this->url('post', ['action' => 'index'],
                    ['query' => ['tag' => $tagId]]); ?>">

                    <span style="font-size:<?= $this->escapeHtml(0.9 + $tag['count'] * 2) ?>em">
                        <?= $this->escapeHtml($tag['name']); ?>
                    </span>

                </a>

            <?php } ?>
        </div>
    </div>


    <!--    some text-->
    <!--    <table class="table">-->
    <!--        <thead>-->
    <!--        <th>1</th>-->
    <!--        <th>2</th>-->
    <!--        </thead>-->
    <!--        <tbody>-->
    <!--        <tr>-->
    <!--            <td>3</td>-->
    <!--            <td>4</td>-->
    <!--        </tr>-->
    <!--        <tr>-->
    <!--            <td>5</td>-->
    <!--            <td>6</td>-->
    <!--        </tr>-->
    <!--        </tbody>-->
    <!--    </table>-->
</div>