<?php $post = $this->post; ?>

<div class="row">
    <div class="col-md-9">
        <h1 class="display-4"><?php echo $post->getTitle() ?></h1>
    </div>
    <div class="col-md-3">
        <?php if ($post->isAuthor($this->identity()) && $post->canBeEdit()) { ?>
            <a href="/post/edit/<?php echo $post->getId() ?>" class="btn btn-outline-dark">Edit</a>
        <?php } ?>
        <?php if ($post->isAuthor($this->identity())) { ?>
            <a href="/post/delete/<?php echo $post->getId() ?>" class="btn btn-outline-dark">Delete</a>
        <?php } ?>
    </div>
</div>


<b><span class="text-muted">Author: </span></b>
<i><span class="text-muted"><?php echo $post->getUser()->getLogin() ?></span></i>
<b><span class="text-muted">Date: </span></b>
<i><span class="text-muted"><?php echo $post->getDate() ?></span></i>

<p class="lead" style="margin: 10px 0 10px 0"><?php echo $post->getContent() ?></p>

<b>Tags:</b>
<?php
$count = count($post->getTags()) - 1;
foreach ($post->getTags() as $key=>$tag) { ?>
    <a href="/post?tag=<?php echo $tag->getId()?>">
        <?php echo $tag->getName()?></a
    ><?php if ($key != $count) {
            echo ',';
        } ?>
<?php } ?>

<?php
$form = $this->form;
$form->prepare();

$form->get('content')->setAttributes([
    'class' => 'form-control',
    'style' => 'width: 40%'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-success',
]);
?>
<hr>
<div>
    <?php echo $this->form()->openTag($form) ?>

    <div class="form-inline">
        <?php
        echo $this->formLabel($form->get('content'));
        echo $this->formElement($form->get('content'));
        echo $this->formElementErrors($form->get('content'));
        echo $this->formElement($form->get('submit'));
        ?>
    </div>

    <?php echo $this->form()->closeTag($form) ?>
</div>

<div class="style-container">
    <ul class="list-group">
        <?php foreach ($this->comments as $comment) { ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">

                <span><?php echo $comment->getContent() ?></span>
                <span class="badge badge-dark badge-pill">
                    <?php echo $comment->getUser()->getLogin() ?>
                    <?php echo $comment->getDate() ?>
                </span>
            </li>
        <?php } ?>
    </ul>

    <br>
    <?php
    echo $this->paginationControl($this->comments,
        'Sliding',
        'application/partial/paginator',
        ['route' => 'post', 'action' => 'one', 'id' => $post->getId()]);
    ?>

</div>