<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.structure.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.theme.min.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('fonts/fontawesome-all.js'))
            ->prependFile($this->basePath('js/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">-->
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <div class="container-fluid" style="width: 90%">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('post') ?>">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('profile') ?>">Profile</a>
                </li>
                <li class="nav-item">
                    <?php if ($this->identity() == null) { ?>
                        <a class="nav-link" href="<?= $this->url('login') ?>">Login</a>
                    <?php } else { ?>
                        <a class="nav-link" href="<?= $this->url('logout') ?>">Logout</a>
                    <?php } ?>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid style-container">
    <?= $this->content ?>
    <hr>
    <footer>
        <!--                <p>&copy; 2005 - -->
        <? //= date('Y') ?><!-- by Zend Technologies Ltd. All rights reserved.</p>-->
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
