<?php if ($this->pageCount) {
    $params = $this->params; ?>

    <nav>
        <ul class="pagination">

            <!-- Previous page link -->
            <?php if (isset($this->previous)) {
                $params['page'] = $this->previous; ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $this->url($this->route, ['action' => $this->action, 'id' => $this->id],
                           ['query' => $params]); ?>"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php } else { ?>
                <!--                <li class="page-item page-link">-->
                <!--                    <span aria-hidden="true">&laquo;</span>-->
                <!--                </li>-->
            <?php } ?>

            <!-- Numbered page links -->
            <?php
            if (count($this->pagesInRange) > 1) {
                foreach ($this->pagesInRange as $page) { ?>
                    <?php if ($page != $this->current) {
                        $params['page'] = $page; ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="<?= $this->url($this->route, ['action' => $this->action, 'id' => $this->id],
                                   ['query' => $params]); ?>"><?= $this->escapeHtml($page); ?></a>
                        </li>
                    <?php } else { ?>
                        <li class="page-item page-link">
                            <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                        </li>
                    <?php } ?>
                <?php }
            } ?>

            <!-- Next page link -->
            <?php if (isset($this->next)) {
                $params['page'] = $this->next; ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?php echo $this->url($this->route, ['action' => $this->action, 'id' => $this->id],
                           ['query' => $params]); ?>"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php } else { ?>
                <!--                <li class="page-item page-link">-->
                <!--                    <span aria-hidden="true">&raquo;</span>-->
                <!--                </li>-->
            <?php } ?>

        </ul>
    </nav>

<?php } ?>